WebApplication2/Controllers/MyRequestController.cs
using GatePass_Project.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using GatePass_Project.DataAccess.MyRequest;

namespace GatePass_Project.Controllers
{
    public class MyRequestController : Controller
    {
        private readonly ILogger<MyRequestController> _logger;
        private readonly MyRequestRepository _myRequestRepository;


        public MyRequestController(ILogger<MyRequestController> logger, MyRequestRepository myRequestRepository)
        {
            _logger = logger;
            _myRequestRepository = myRequestRepository;

        }

        public IActionResult MyRequest()
        {
           
            
            var serviceNo = HttpContext.Session.GetString("UserName");
            ViewBag.UserName = serviceNo;
            List<MyRequestModel> requests = _myRequestRepository.GetRequests(serviceNo);
            return View(requests);
        }

        public IActionResult RequestStatus(int id)
        {

            var sessionUserName = HttpContext.Session.GetString("UserName");
            ViewBag.UserName = sessionUserName;

            MyRequestModel requestStatus = _myRequestRepository.GetRequestStatusById(id);

            if (requestStatus == null)
            {
                return RedirectToAction("Error");
            }

            int requestRefNo = _myRequestRepository.GetRequestRefNoById(id);
            requestStatus.Request_ref_no = requestRefNo;

            return View(requestStatus);
        }

        public IActionResult MyRequestItemDetail(int id)
        {

            var sessionUserName = HttpContext.Session.GetString("UserName");
            ViewBag.UserName = sessionUserName;

            List<MyRequestModel> items = _myRequestRepository.GetDetailsById(id);

            if (items.Count == 0)
            {
                return RedirectToAction("Error");
            }

            return View(items);
        }
        
        //public IActionResult MyRequestDetails(int id)
        //{
            //MyRequestModel item = _myRequestRepository.GetRequestDetailsByRefNo(id);

            //if (item == null)
           // {
               // return RedirectToAction("Error");
            //}

            //return View(item);
        //}
    }
}

WebApplication2/Views/MyRequest/MyRequest.cshtml
@model List<GatePass_Project.Models.MyRequestModel>

@{
    ViewData["Title"] = "My Request";
}

<div class="text-center">
    <h1 class="display-4" style="font-size: 30px;">My Request</h1>
</div>
<br>

<div class="form-group">
    <div class="row">
        <div class="col-6">
            @* <span>Show Entries </span> *@
            <select id="pageSizeDropdown" class="form-control" style="width:450px; display: inline-block; margin: 0 auto;">
                <option value="" disabled selected hidden>Select the number of entries</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="5">5</option>
                <option value="10">10</option>
                <option value="50">50</option>
            </select>
        
            <button id="resetButton" class="btn btn-danger text-decoration-none" style="margin-left: 5px;">Reset</button>
        </div>
    </div>
</div>
<br>
<br />

<!-- My request table -->
<div class="MyRequest-Container_row2">
    <div class="">
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th scope="col">Ref.No</th>
                    <th scope="col">Emp Name</th>
                    <th scope="col">Sender Serv.No</th>
                    <th scope="col">In Location</th>
                    <th scope="col">Out Location</th>
                    <th scope="col">Receiver Serv.No</th>
                    <th scope="col">Created Date Time</th>
                    <th scope="col">EO Service No</th>
                    <th scope="col">Carrier NIC</th>
                    <th scope="col">Actions</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var request in Model)
                {
                    <tr>
                        <td>@request.Request_ref_no</td>
                        <td>@request.Name</td>
                        <td>@request.Sender_service_no</td>
                        <td>@request.In_location_name</td>
                        <td>@request.Out_location_name</td>
                        <td>@request.Receiver_service_no</td>
                        <td>@request.Created_date</td>
                        <td>@request.ExO_service_no</td>
                        <td>@request.Carrier_nic_no</td>
                        <td>
                            <div class="d-inline">
                                <a href="@Url.Action("MyRequestItemDetail", "MyRequest", new { id = request.Request_ref_no })" class=""><button class="btn btn-sm text-decoration-none btn-primary">View Item Details</button></a>
                            </div>
                        </td>

                        <td>
                            <div class="d-inline">
                                <a href="@Url.Action("RequestStatus", "MyRequest", new { id = request.Request_ref_no })" class=""><button class="btn btn-sm text-decoration-none btn-primary">Status</button></a>
                            </div>
                        </td>
                        <!-- <td>
                             <div class="d-inline">
                                 <a href="@Url.Action("MyRequestDetails", "MyRequest", new { id = request.Request_ref_no })" class=""><button class="btn btn-sm text-decoration-none btn-primary">PDF</button></a>
                             </div>
                         </td>
                          -->
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<!-- Include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<script>
    $(document).ready(function () {
        // Dropdown change event
        $("#pageSizeDropdown").change(function () {
            var selectedValue = $(this).val();
            var rowsToDisplay = parseInt(selectedValue);

            // Show/hide rows based on the selected value
            $(".MyRequest-Container_row2 table tbody tr").hide();
            $(".MyRequest-Container_row2 table tbody tr:lt(" + rowsToDisplay + ")").show();
        });

        // Reset button click event
        $("#resetButton").click(function () {
            // Show all rows
            $(".MyRequest-Container_row2 table tbody tr").show();
        });
    });
</script>

<style>
    .table {
        font-size: 13px;
        border-spacing: 0 15px;
        width: 100%;
    }

        .table th {
            background-color: #f5f5f5;
            font-weight: bold;
        }

        .table td {
            background-color: #ffffff;
            border: 1px solid #333;
            padding: 10px;
        }
    /* Custom style for buttons */
    .btn {
        border-radius: 5px;
        padding: 5px 10px;
        text-decoration: none;
        margin-right: 5px;
        cursor: pointer;
    }

        /* Hover style for buttons */
        .btn:hover {
            text-decoration: underline;
        }

    /* Custom styles for button colors */
    .btn-success {
        background-color: #28a745; /* Green color for "Verify" button */
        color: #fff; /* White text color */
    }

    .btn-danger {
        background-color: #dc3545; /* Red color for "Reject" button */
        color: #fff; /* White text color */
    }

    a {
        text-decoration: none;
        color: inherit;
    }
</style>

WebApplication2/Views/MyRequest/MyRequestDetails.cshtml
@model GatePass_Project.Models.MyRequestModel

<h2>@Model.Returnable_status</h2>
   

WebApplication2/Views/MyRequest/MyRequestItemDetail.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>


<style>
    .imgContainer {
        margin-top: 25px;
    }
</style>

<div class="container">
    <h1 class="custom-font" style="font-size: 28px;">My Items Details</h1>
</div>

<br />

<div class="card">
    <div class="card-body">
        <h5 class="card-title custom-font">Ref. No: @Model[0].Request_ref_no</h5>
        @{
           
        var base64String = "";
        }

        @foreach (var item in Model)
        {
         
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-4">
                            Item ID
                        </div>
                        <div class="col">
                            : @item.Item_id
                            
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-4">
                            Item Serial No
                        </div>
                        <div class="col">
                            : @item.Item_serial_no
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-4">
                            Item Name
                        </div>
                        <div class="col">
                            : @item.Item_name
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-4">
                            Item Description
                        </div>
                        <div class="col">
                            : @item.Item_Description
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-4">
                            Item Quantity
                        </div>
                        <div class="col">
                            : @item.Item_Quantity
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-4">
                            Item Returnable status
                        </div>
                        <div class="col">
                            : @(item.Returnable_status)
                        </div>
                    </div>


                    <div class="container  p-0 imgContainer">
                        <div>
                            <button type="button" class="btn btn-primary btn-sm" onclick="toggleItemPhotosForm(@item.Item_id)">View Item Images</button>
                        </div>
                    </div>

                    <div>
                        <br>
                    </div>
                   
                    <div class="container">
                        <form id="itemPhotosForm-@item.Item_id" style="display:none">
                            <div class="form-group">
                                @if (item.Attaches != null && item.Attaches.Length > 0)
                                {
                                    <p>Image Data Found</p>
                                     base64String = Convert.ToBase64String(item.Attaches);
                                    <img src="data:image;base64,@base64String" style="max-width: 35%;" />
                                }
                                else
                                {
                                    <p>No image available</p>
                                }
                            </div>

                        </form>
                        <div class="m-2 float-end">
                            <a asp-action="MyRequest"><button class="btn btn-sm text-decoration-none btn-secondary">Back to List</button></a>
                        </div>
                    </div>
                    <!--Print-->
                    <div class="mt-3">
                        <button type="button" class="btn btn-success btn-sm" onclick="generatePdf('@Model[0].Request_ref_no','@item.Item_id', '@item.Item_serial_no', '@item.Item_name', '@item.Item_Description','@item.Item_Quantity', '@item.Returnable_status','@base64String')">Generate PDF</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<script>
    function toggleItemPhotosForm(itemId) {
        const itemPhotosForm = document.getElementById(`itemPhotosForm-${itemId}`);
        if (itemPhotosForm.style.display === "none" || itemPhotosForm.style.display === "") {
            itemPhotosForm.style.display = "block";
        } else {
            itemPhotosForm.style.display = "none";
        }
    }
    //Generate pdf dcoument
    async function generatePdf(request_ref_no, itemId, serialNo, name, description, itemquantity, returnableStatus, base64String) {
        const { jsPDF } = window.jspdf;

        // Load Poppins Font
        const fontUrl = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff';
        const font = await fetch(fontUrl).then(response => response.arrayBuffer());

        const doc = new jsPDF();

        // Add Poppins font
        doc.addFileToVFS("Poppins-Regular.ttf", font);
        doc.addFont("Poppins-Regular.ttf", "Poppins", "normal");
        doc.setFont("Poppins");

        // Title
        doc.setFontSize(20);
        doc.setTextColor(0, 0, 128); // Navy blue
        doc.setFont("Poppins", "bold");
        doc.text('SLT Gate Pass Item Details Document', 35, 38);

        // Item Details in Table Format
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);

        const details = [
            ['Request Reference No', request_ref_no],
            ['Item ID', itemId],
            ['Item Serial No', serialNo],
            ['Item Name', name],
            ['Item Description', description],
            ['Item Quantity', itemquantity],
            ['Item Returnable Status', returnableStatus]
        ];

        let startY = 50; // Adjusted starting Y position for the table

        const cellWidth = 90; // Adjusted cell width for better centering
        const cellHeight = 8; // Reduced cell height
        const tableStartX = (doc.internal.pageSize.getWidth() - (cellWidth * 2)) / 2; // Center the table

        details.forEach(([label, value], index) => {
            doc.text(label, tableStartX + 2, startY + 6 + (index * cellHeight));
            doc.text(value, tableStartX + cellWidth + 2, startY + 6 + (index * cellHeight));
        });

        // If image data is available, add it to the PDF
        if (base64String) {
            const itemImg = new Image();
            itemImg.src = `data:image/jpeg;base64,${base64String}`;
            await itemImg.decode(); // Wait for the image to load
            doc.addImage(itemImg, 'JPEG', (doc.internal.pageSize.getWidth() - 80) / 2, startY + details.length * cellHeight + 10, 80, 80); // Adjusted image size and centered
        }

        // Add line above footer
        const lineY = 280; // Adjust Y position as needed
        doc.setLineWidth(0.5);
        doc.line(10, lineY, doc.internal.pageSize.getWidth() - 10, lineY);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text('Generated by SLT System', 10, lineY + 10);

        doc.save(`ItemDetails_${request_ref_no}.pdf`);
    }

</script>

WebApplication2/Views/MyRequest/RequestStatus.cshtml
@model GatePass_Project.Models.MyRequestModel

@{
    ViewData["Title"] = "Request Status";
}

<div class="text-center">
    <h1 class="display-4" style="font-size: 30px;">Request Status</h1>
</div>
<br></br>

<div class="container">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title custom-font">Ref. No: @Model.Request_ref_no</h5>

            <p class="card-text custom-font">Progress Status: @Model.Progress_status</p>

            <a asp-action="MyRequest">Back to List</a>
        </div>
    </div>
</div>